### ISSUE TITLE
起動できない。

### ISSUE THREAD

**Issue by kinchanramen** [puk06/Avatar-Explorer#1]
とても興味深いソフトウェアを開発してくださりありがとうございます！
boothよりzipファイルをダウンロードしファイルを解凍してからexeファイルをダブルクリックして起動してみたところ、何も反応が無くソフトウェアが起動しませんでした。
私のPC環境は以下の通りとなっております。
・.NET 8.0 インストール済み
・Visual Studio 2022 インストール済み
・解凍したフォルダはC:\Users\hoge\Documents\に配置
もしもおま環であったら申し訳ありませんが、対応のほどお願い申し上げます

**Comment by puk06** [comment]
ウイルス対策などで削除されてるファイルなどありませんか？
こちらがファイル一覧となっていますが、欠けているものなどございませんかね？
![image](https://github.com/user-attachments/assets/a1e34bb9-3b49-4fa9-bb8b-92d54d8fa745)

**Comment by kinchanramen** [comment]
返信ありがとうございます。一応windows defenderの除外設定もしており、ウイルス対策等で削除されているファイル等も無さそうです。
![image](https://github.com/user-attachments/assets/9d9a1b45-05c7-4681-9fb5-315030176601)
![image](https://github.com/user-attachments/assets/7cd5b82c-e39d-45b1-b28b-80b3473ade8e)

**Comment by puk06** [comment]
原因がわからないので、私の別のパソコンでテストしてみます。少し時間がかかるかも知れません。

**Comment by kinchanramen** [comment]
お手数おかけいたします。感謝いたします。🙇

**Comment by hiwaitan** [comment]
こちらの環境ではDatasフォルダにある「NotoSansJP-Regular.ttf」を開いてインストールすることで起動できるようになりました

**Comment by kinchanramen** [comment]
hiwaitanさんの言う通りにフォントをインストールすると起動することができました。puk06さんとhiwaitanさんありがとうございます🙇
