### ISSUE TITLE
アイテムを追加した際、左の欄を更新して欲しい

### ISSUE THREAD

**Issue by NanamoAlma** [puk06/Avatar-Explorer#11]
( v1.0.1-Testで確認  )

アイテムを追加した際、左の欄が更新されておりません。
そのため、新規のカテゴリのアイテムを追加した際、
項目が表示されないため、アイテムを選択できない状態になっております。

現状アバターや作者の欄から探すか、アプリケーションを再起動する事で更新され、回避できるものの、少々手間でして...

アイテムを追加した際に左の欄を更新するか、
更新ボタンを追加していただけると、とても嬉しいです。

**Comment by puk06** [comment]
ドラッグアンドドロップ時の画面更新を忘れていました。ありがとうございます！
