### ISSUE TITLE
アイテムを右クリックしたときの「削除」の位置について

### ISSUE THREAD

**Issue by hiwaitan** [puk06/Avatar-Explorer#6]
アイテムを右クリックしたときに表示されるメニューですが、「削除」項目が上の方にあるのが気になりました。
下の方にあるのが自然かな？と思うのですがいかがでしょうか？
例えば
- サムネイル変更
- 編集
- 削除

といった感じで…

あと、削除前に確認メッセージを表示したほうがいいかな？とも思いました。

**Comment by puk06** [comment]
わかりました。直しておきます！
