### ISSUE TITLE
アイテムの追加・編集画面周りの挙動について

### ISSUE THREAD

**Issue by hiwaitan** [puk06/Avatar-Explorer#7]
数点ありますが同じ画面なのでまとめて失礼します…

アイテムの追加

1. フォルダとマテリアルのテキストボックスに「aaaa」等適当に入れた後、「カスタムで追加」ボタンを押下して
タイトルと作者を入力すると、フォルダチェックをパスして項目の追加ができてしまいます。

追加できちゃった後にアイテム一覧でアイテムをクリックした際、フォルダがないとエラーで落ちるので、ここにも存在チェック処理あるといいと思います。
メッセージダイアログで編集・削除・キャンセルがボタンで選べると親切かもしれません。

アイテムの編集

1. フォルダとマテリアルのテキストボックスが有効状態と無効状態で混在しているので、合わせたほうがいいかなと思いました。
2. フォルダを選択するボタンのテキストは「フォルダを開く」よりも「フォルダを選択」のほうが自然かもしれません。
3. タイプがアバターの項目を編集する際、タイプを「衣装」に変更し、「対応アバター」選択画面を表示すると
編集中の項目が選択できてしまうので一覧から除外していい気もします。

ちょっと多いですがご確認いただければ幸いです。
よろしくお願いいたします。

**Comment by puk06** [comment]
わかりました！修正しておきます
