### ISSUE TITLE
未所持アバター

### ISSUE THREAD

**Issue by kairingo0020** [puk06/Avatar-Explorer#8]
当方未所持アバターの衣装を購入して非対応ながら無理やり着せているので、未所持アバターというフォルダを作成し
下に添付の通りにアイテムを追加しました(Booth URLは省略して登録したところスクショの通りのurlに置き換えられた)

![スクリーンショット 2024-12-22 163607](https://github.com/user-attachments/assets/9bf63d71-2a0e-44cb-90f7-1f077ea762b9)
![image](https://github.com/user-attachments/assets/9d8f198b-980d-4fb3-b14b-7af6bcaf6fb0)

そして対応アバターをクリックしたところエラーが出ました
![スクリーンショット 2024-12-22 164113](https://github.com/user-attachments/assets/6f089fa7-bdb3-4990-9141-74006052f4ce)

エラー文をそのままtxtで添付します
[エラー.txt](https://github.com/user-attachments/files/18221127/default.txt)

対応よろしくお願いします

**Comment by puk06** [comment]
修正済みです！v1.0.1で治ります！

**Comment by kairingo0020** [comment]
ぎゃーーーーすいません　よく見てませんでした！！！！

Twitterのこと忘れてて今見たら見つけました()

**Comment by puk06** [comment]
全然大丈夫です！！リリースまで少々お待ち下さいー！

**Comment by puk06** [comment]
ちなみに、現在修正したり追加したりしてるものはBoothの説明欄の一番下に書いてあるので、そこも参考にしてくれると嬉しいです！

**Comment by puk06** [comment]
参考程度にですが、
- 「カスタムで追加」したアバターが存在する場合、エラーで終了してしまうのを修正 - hiwaitan
- BoothIDが-1のものを編集するときにリンクが自動生成されるのを削除
これらがこのIssueの解決にあたる部分です！
